# Generated by Django 5.1.2 on 2025-01-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_representation_location_unique_slug_website_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='show',
            constraint=models.UniqueConstraint(fields=('slug', 'created_at'), name='unique_slug_created_at'),
        ),
    ]
