# Generated by Django 5.1.2 on 2025-01-11 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_remove_artist_types_artist_unique_firstname_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='artistTypes', to='catalogue.artist')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='_artistTypes', to='catalogue.type')),
            ],
            options={
                'db_table': 'artist_type',
            },
        ),
    ]
