# Generated by Django 5.1.2 on 2025-01-11 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_artisttypeshow_show_artist_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisttype',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='a_artistTypes', to='catalogue.artist'),
        ),
        migrations.AlterField(
            model_name='artisttype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='t_artistTypes', to='catalogue.type'),
        ),
    ]
